FROM dhi.io/nginx:1-alpine3.21-dev

EXPOSE 8080

LABEL org.opencontainers.image.title="Nginx 1 Alpine Dev"
LABEL org.opencontainers.image.description="Nginx 1 Alpine Dev Docker Image based on the docker hardened nginx image."
LABEL status="supported"
